name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install codespell flake8
      - run: codespell --ignore-words-list="ned,positionned" # --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
